services:
  app:
    build: .
    environment:
      PORT: 8000
      DRIVER: "mysql"
      ADDRESS: "database-1.c6hhzms8iiky.ap-southeast-1.rds.amazonaws.com"
      DB_PORT: 3306
      USERNAME: "admin"
      PASSWORD: "aryadewangga"
      NAME: "project_ecommerce_k2"
    restart: always
    ports:
      - 8081:8000
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080